- name: Install MySQL
  user: adminuser
  hosts: mysql
  become: True
  become_user: root
  vars:
    MySQL_root_pass: kingpin42330@
  tasks:
    - name: test installation
      apt: package={{ item }} state=present force=yes update_cache=yes cache_valid_time=3600
      when: ansible_os_family == "Debian"
      with_items:
        - mysql-server
        - mysql-client
        - python3-mysqldb